"use client";

import { Inter } from 'next/font/google'
import { Navbar } from './components/navBar/navBar';
import Link from 'next/link';
import React from 'react';
import { ChakraProvider } from '@chakra-ui/react';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import './globals.css'
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AB Clothing Store',
  description: 'Generated by Mandolesi, Bruno and Mazzino Albano.',
}

const ShopContextProvider = dynamic(() => import('./context/shop-context').then(mod => mod.ShopContextProvider), {
  ssr: false
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <ShopContextProvider>
            <ToastContainer
              position="bottom-left"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={true}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
            <Navbar />
            {children}
            <footer>
              <Link href="https://github.com/iaw-2023/Digital-Daredevils-js/">
                <p>Created by Digital Daredevils ®</p>
              </Link>
            </footer>
          </ShopContextProvider>
        </ChakraProvider>
      </body>
    </html>
  )
}